### ISSUE TITLE
help please :D

### ISSUE THREAD

**Issue by ickyspot** [adammhaile/Elpis#65] opened 2015-06-28 03:32 UTC
I need help elpis has stopped working with this error any chance on helping out is awesomely appreciated! 

PandoraSharp.Exceptions.PandoraException: Failed to load song more than once.
Check connection and try again. ---> BassPlayer.BassStreamException: Bass Error: Unable to create stream - BASS_ERROR_TIMEOUT
   at BassPlayer.BassAudioEngine.Play(String filePath)
   at PandoraSharpPlayer.Player.PlayNextSong(Int32 retry)
   --- End of inner exception stack trace ---
   at PandoraSharpPlayer.Player.PlayNextSong(Int32 retry)
   at PandoraSharpPlayer.Player.PlayNextSong(Int32 retry)
   at PandoraSharpPlayer.Player.PlayNextSong(Int32 retry)
   at PandoraSharpPlayer.Player.PlayThread()
   at PandoraSharpPlayer.Player.<>c__DisplayClass1.<RunTask>b__0()

**Comment by seliver** [comment] 2015-06-28 17:03
This basically a duplicate of issies #34 and #50, where there reason is alredy explained. In resume: not Elpis fault.
Closing this.

**Closed by seliver** 2015-06-28 17:03 UTC
