### ISSUE TITLE
Failed to load song more than once.

### ISSUE THREAD

**Issue by d503364** [adammhaile/Elpis#67] opened 2015-07-15 17:15 UTC
PandoraSharp.Exceptions.PandoraException: Failed to load song more than once.
Check connection and try again. ---> BassPlayer.BassStreamException: Bass Error: Unable to create stream - BASS_ERROR_TIMEOUT
   at BassPlayer.BassAudioEngine.Play(String filePath)
   at PandoraSharpPlayer.Player.PlayNextSong(Int32 retry)
   --- End of inner exception stack trace ---
   at PandoraSharpPlayer.Player.PlayNextSong(Int32 retry)
   at PandoraSharpPlayer.Player.PlayNextSong(Int32 retry)
   at PandoraSharpPlayer.Player.PlayNextSong(Int32 retry)
   at PandoraSharpPlayer.Player.PlayThread()
   at PandoraSharpPlayer.Player.<>c__DisplayClass3.<RunTask>b__2()

**Comment by seliver** [comment] 2015-07-17 15:03
This is a duplicate of issue #34. 
As far as I know, it's not an Elpis issue.

**Closed by seliver** 2015-07-17 15:03 UTC
