### ISSUE TITLE
Failed to load song more than once

### ISSUE THREAD

**Issue by ChikNoods** [adammhaile/Elpis#50] opened 2015-04-25 21:20 UTC
Fresh install on Win7. Havnt been able to listen to a song yet. I have this on my other PC and it works fine, but its not the newest version.

PandoraSharp.Exceptions.PandoraException: Failed to load song more than once.
Check connection and try again. ---> BassPlayer.BassStreamException: Bass Error: Unable to create stream - BASS_ERROR_TIMEOUT
   at BassPlayer.BassAudioEngine.Play(String filePath)
   at PandoraSharpPlayer.Player.PlayNextSong(Int32 retry)
   --- End of inner exception stack trace ---
   at PandoraSharpPlayer.Player.PlayNextSong(Int32 retry)
   at PandoraSharpPlayer.Player.PlayNextSong(Int32 retry)
   at PandoraSharpPlayer.Player.PlayNextSong(Int32 retry)
   at PandoraSharpPlayer.Player.PlayThread()
   at PandoraSharpPlayer.Player.<>c__DisplayClass1.<RunTask>b__0()

**Comment by seliver** [comment] 2015-04-26 22:36
This is a duplicate of issue #34 
Basically it is caused by pandora blocking your account temporarily.

**Closed by seliver** 2015-04-26 22:36 UTC

**Comment by ChikNoods** [comment] 2015-04-26 23:11
I dont skip songs though. I listen to pandora as ambient music, so I dont control it. And I can load pandora up in firefox and listen just fine. As I'm typing this. I am using Elpis on my other machine. I didnt not update when it asked me to. It's working perfectly fine as intended

**Comment by seliver** [comment] 2015-04-27 10:22
But are you trying to use Elpis on another pc with the same account at 
the same time?

Alexey

**Comment by ChikNoods** [comment] 2015-04-27 14:37
I am not. I didnt even load the program on the desktop machine the same day as the laptop. I use pandora on my desktop, laptop and cellphone. Never are they running at the same time or within 2 hours of each other. I'm going to load the same version from the laptop onto th desktop and see how it works. 1.4.6

**Comment by ickyspot** [comment] 2015-06-29 00:20
This isnt the same issue the problem is that its just not loading at all upon start up clean installs and updates.  I only use pandora in one spot and that is my desktop.

**Comment by seliver** [comment] 2015-06-29 00:22
Try and see if there's no Elpis process already running.

Alexey

Às 01:20 de 29/06/2015, ickyspot escreveu:

**Comment by adammhaile** [comment] 2015-06-29 00:22
Sorry to disappoint you but this is an all too common issue and NOT one
that Elpis has any control over. It's your network. For some reason, your
connection to pandora is being refused. Try it from another computer and
preferably on a different network.

**Comment by ickyspot** [comment] 2015-06-29 05:07
I don't really feel disappointed over an issue from a piece of freeware.  I'm just disappointed that there is no support especially if you are looking for donations.  Enjoy writing your Elpis you lost a donation.
