### ISSUE TITLE
Error initializing the player engine

### ISSUE THREAD

**Issue by lehet005** [adammhaile/Elpis#122] opened 2016-04-08 04:12 UTC
Here is the error report:

```csharp
BassPlayer.BassException: BASS: Initialize failed. Reason: }Init Error: BASS_ERROR_UNKNOWN
   at BassPlayer.BassAudioEngine.InitBass()
   at PandoraSharpPlayer.Player.Initialize(String bassRegEmail, String bassRegKey)
   at Elpis.MainWindow.FinalLoad()
```

**Comment by seliver** [comment] 2016-04-11 09:58
this is a duplicate of #32. Have a read there ;)

**Closed by seliver** 2016-04-11 09:58 UTC
