### ISSUE TITLE
Elpis crashes in Windows 10

### ISSUE THREAD

**Issue by bkilpat01** [adammhaile/Elpis#95] opened 2015-10-20 08:43 UTC
Elpis crashes immediately upon opening. I get the following error:

BassPlayer.BassException: BASS: Initialize failed. Reason: }Init Error: BASS_ERROR_UNKNOWN
   at BassPlayer.BassAudioEngine.InitBass()
   at PandoraSharpPlayer.Player.Initialize(String bassRegEmail, String bassRegKey)
   at Elpis.MainWindow.FinalLoad()

**Comment by seliver** [comment] 2015-10-24 12:53
This is another duplicate of issue #32 . Not an Elpis problem, basically. Wait a few days and it will start working again.

**Closed by seliver** 2015-10-24 12:53 UTC
