### ISSUE TITLE
Elpis can't start "All hope is lost" error

### ISSUE THREAD

**Issue by pgorbas** [adammhaile/Elpis#94] opened 2015-10-15 01:22 UTC
BassPlayer.BassException: BASS: Initialize failed. Reason: }Init Error: BASS_ERROR_UNKNOWN
   at BassPlayer.BassAudioEngine.InitBass()
   at PandoraSharpPlayer.Player.Initialize(String bassRegEmail, String bassRegKey)
   at Elpis.MainWindow.FinalLoad()

**Comment by seliver** [comment] 2015-10-15 22:38
This is a duplicate of issue #32 . Closing this.

**Closed by seliver** 2015-10-15 22:38 UTC
Labels: duplicate
