### ISSUE TITLE
Feature Request: Global Hotkey for Volume Up/Down

### ISSUE THREAD

**Issue by eumoria** [adammhaile/Elpis#103] opened 2015-12-14 20:49 UTC
The global hotkeys for skipping, thumbs up/down are excellent is there a possibility of adding volume up/down as an option? Thank you!

**Comment by Wires77** [comment] 2016-02-14 15:36
This seems like a duplicate of #64

**Comment by seliver** [comment] 2016-06-16 07:43
Indeed a duplicate.

**Closed by seliver** 2016-06-16 07:43 UTC
Labels: feature request
